# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  cbor_metadata = false
  emv_version = "paris"
  fuzz = { runs = 1_000 }
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  solc = "0.8.19"
  src = "src"
  test = "test"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
